name: 'mobile_money_fraud_analytics'
version: '1.0.0'
config-version: 2

profile: 'mobile_money_fraud_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mobile_money_fraud_analytics:
    staging:
      +materialized: view
      +schema: staging
    fraud:
      +materialized: table
      +schema: fraud
    marts:
      +materialized: table
      +schema: marts
